// nigeriaStates.js
export const nigeriaStates = [
  { title: "Abia" },
  { title: "Adamawa" },
  { title: "Akwa Ibom" },
  { title: "Anambra" },
  { title: "Bauchi" },
  { title: "Bayelsa" },
  { title: "Benue" },
  { title: "Borno" },
  { title: "Cross River" },
  { title: "Delta" },
  { title: "Ebonyi" },
  { title: "Edo" },
  { title: "Ekiti" },
  { title: "Enugu" },
  { title: "Gombe" },
  { title: "Imo" },
  { title: "Jigawa" },
  { title: "Kaduna" },
  { title: "Kano" },
  { title: "Katsina" },
  { title: "Kebbi" },
  { title: "Kogi" },
  { title: "Kwara" },
  { title: "Lagos" },
  { title: "Nasarawa" },
  { title: "Niger" },
  { title: "Ogun" },
  { title: "Ondo" },
  { title: "Osun" },
  { title: "Oyo" },
  { title: "Plateau" },
  { title: "Rivers" },
  { title: "Sokoto" },
  { title: "Taraba" },
  { title: "Yobe" },
  { title: "Zamfara" },
  { title: "Federal Capital Territory (Abuja)" }
];

export const nigeriaBanks = [
  { title: "Access Bank", icon:"🛳"},
  { title: "Zenith Bank" },
  { title: "Guaranty Trust Bank (GTBank)" },
  { title: "First Bank of Nigeria" },
  { title: "United Bank for Africa (UBA)" },
  { title: "Fidelity Bank" },
  { title: "Union Bank" },
  { title: "Stanbic IBTC Bank" },
  { title: "Polaris Bank" },
  { title: "Sterling Bank" },
  { title: "Wema Bank" },
  { title: "Ecobank Nigeria" },
  { title: "Heritage Bank" },
  { title: "Keystone Bank" },
  { title: "Jaiz Bank" }
]