const driverData = [
  {
    id: 1,
    name: "John Ndubuisi Chukwumeka",
    distance: "5 mins away from you",
    price: "₦2,000",
    rating: 4.2,
    reviews: 42,
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    location: "UNN Hostel Block A, Faculty of Arts Gate",
    plateNumber: "MRT12235",
    vehicleType: "Car",
    model: "Toyota Camry LA 2003",
    seats: 4,
  },
  {
    id: 2,
    name: "Ronald Richards",
    distance: "10 mins away from you",
    price: "₦1,500",
    rating: 3.6,
    reviews: 12,
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    location: "UNN Main Gate",
    plateNumber: "XYZ1234",
    vehicleType: "Car",
    model: "Honda Accord 2010",
    seats: 4,
  },
  {
    id: 3,
    name: "Jerome Bell",
    distance: "20 mins away from you",
    price: "₦3,500",
    rating: 4.9,
    reviews: 125,
    image: "https://randomuser.me/api/portraits/men/51.jpg",
    location: "UNN Faculty of Sciences",
    plateNumber: "JKL5678",
    vehicleType: "Car",
    model: "Lexus RX 2018",
    seats: 4,
  },
];

export default driverData;
