export const data = [
  {
    id: "1",
    name: "Chibuike Emmanuel Nwachukwu",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    eta: "5 mins",
    currentLocation: "University of Lagos",
    destination: "Yaba Market",
    fare: "₦2,500",
    rideType: "Standard",
    status: "Pending",
    date: "2023-10-01",
    pickup: "University Main Gate",
    luggage: [
      "https://randomuser.me/api/portraits/men/50.jpg",
      "https://randomuser.me/api/portraits/women/44.jpg",
      "https://randomuser.me/api/portraits/men/12.jpg",
    ],
    type: "Standard",
    time: "10:00 AM",
  },
  {
    id: "2",
    name: "Amaka Grace Johnson",
    avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    eta: "12 mins",
    currentLocation: "Lekki Phase 1",
    destination: "Victoria Island",
    fare: "₦3,800",
    rideType: "Premium",
    status: "Ongoing",
    date: "2023-10-03",
    pickup: "Ebeano Supermarket",
    luggage: [
      "https://randomuser.me/api/portraits/men/31.jpg",
      "https://randomuser.me/api/portraits/women/29.jpg",
    ],
    type: "Premium",
    time: "2:45 PM",
  },
  {
    id: "3",
    name: "Ibrahim Musa Abdullahi",
    avatar: "https://randomuser.me/api/portraits/men/77.jpg",
    eta: "8 mins",
    currentLocation: "Ikeja City Mall",
    destination: "Ogba Bus Stop",
    fare: "₦1,700",
    rideType: "Economy",
    status: "Completed",
    date: "2023-09-29",
    pickup: "Shoprite Entrance",
    luggage: [
      "https://randomuser.me/api/portraits/women/14.jpg",
      "https://randomuser.me/api/portraits/men/66.jpg",
    ],
    type: "Economy",
    time: "6:30 PM",
  },
  {
    id: "4",
    name: "Ngozi Ada Okafor",
    avatar: "https://randomuser.me/api/portraits/women/46.jpg",
    eta: "3 mins",
    currentLocation: "CMS Bus Stop",
    destination: "Obalende",
    fare: "₦900",
    rideType: "Bike",
    status: "Cancelled",
    date: "2023-10-05",
    pickup: "Cathedral Church",
    luggage: [],
    type: "Bike",
    time: "9:15 AM",
  },
  {
    id: "5",
    name: "Samuel Olumide Adeyemi",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    eta: "15 mins",
    currentLocation: "Ajah",
    destination: "Ikoyi",
    fare: "₦5,500",
    rideType: "SUV",
    status: "Pending",
    date: "2023-10-06",
    pickup: "Ajah Roundabout",
    luggage: [
      "https://randomuser.me/api/portraits/men/22.jpg",
      "https://randomuser.me/api/portraits/women/33.jpg",
    ],
    type: "SUV",
    time: "8:00 PM",
  },
];
